name: Build LaTeX document
on:
  pull_request:
  push:
  # artifacts expire after 90days, schedule re-generation each month
  # https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#downloading-or-deleting-artifacts
  schedule:
    - cron:  '0 10 * */1 *'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@2.1.0
        with:
          root_file: |
            cv.tex
            cv-en.tex
      - name: Copy pdf files
        run: cp *.pdf index.html public/
      - name: Publish to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
