name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@1.2.1
        with:
          root_file: cv.tex
      - name: Generate artifact
        uses: actions/upload-artifact@v1
        with:
          name: my-curriculum-vitae
          path: cv.pdf

  build_latex_en:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@1.2.1
        with:
          root_file: cv-en.tex
      - name: Generate artifact
        uses: actions/upload-artifact@v1
        with:
          name: my-curriculum-vitae
          path: cv-en.pdf
